"""add cascade delete to user relationships

Revision ID: 084580427e4e
Revises: b644ae5e3dfb
Create Date: 2025-08-14 08:24:59.328022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '084580427e4e'
down_revision: Union[str, Sequence[str], None] = 'b644ae5e3dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_logs_id'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_constraint(op.f('company_information_page_details_user_id_fkey'), 'company_information_page_details', type_='foreignkey')
    op.create_foreign_key(None, 'company_information_page_details', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('subscriptions_subscription_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['subscription_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_subscription_id_fkey'), 'subscriptions', 'users', ['subscription_id'], ['id'])
    op.drop_constraint(None, 'company_information_page_details', type_='foreignkey')
    op.create_foreign_key(op.f('company_information_page_details_user_id_fkey'), 'company_information_page_details', 'users', ['user_id'], ['id'])
    op.create_table('request_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('process_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('additional_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('request_logs_pkey'))
    )
    op.create_index(op.f('ix_request_logs_id'), 'request_logs', ['id'], unique=False)
    # ### end Alembic commands ###
