"""Add trial and usage tracking

Revision ID: ed53e49a8d84
Revises: 9cb1403eabac
Create Date: 2025-07-31 12:21:04.958719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed53e49a8d84'
down_revision: Union[str, Sequence[str], None] = '9cb1403eabac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('trial_used', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('subscriptions', sa.Column('projects_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('subscriptions', sa.Column('documents_uploaded', sa.Integer(), server_default='0', nullable=False))
    op.add_column('subscriptions', sa.Column('queries_made', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('trial_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('trial_expiry_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_expiry_date')
    op.drop_column('users', 'trial_start_date')
    op.drop_column('subscriptions', 'queries_made')
    op.drop_column('subscriptions', 'documents_uploaded')
    op.drop_column('subscriptions', 'projects_used')
    op.drop_column('subscriptions', 'trial_used')
    # ### end Alembic commands ###
